#Choose image
FROM python

#Copy files from local to image
#COPY . .

#PORT
EXPOSE 3000 80 8000

#Install Dependencies
RUN apt update -y && apt install -y git


#Create Directories

#Set working directory
WORKDIR /home/

#Commands to run cli to build image and container
# docker build -t neo:latest .
# docker run -tid -p 80 -v $PWD/:/home -d neo:latest 
# docker exec -it containername bash

